import React, { useState, useEffect, useRef } from "react";
import { 
  ShieldCheck, 
  Database, 
  Link as LinkIcon, 
  Hash, 
  Clock, 
  Activity, 
  ChevronDown,
  RefreshCw,
  Box,
  FileJson,
  Copy,
  Check
} from "lucide-react";
import axios from "axios";

// --- 1. Internal CSS (Matches VitalCare Theme) ---
const customStyles = `
  @keyframes float {
    0%, 100% { transform: translateY(0px) rotate(0deg); }
    50% { transform: translateY(-10px) rotate(2deg); }
  }
  .animate-float-slow { animation: float 6s ease-in-out infinite; }
  
  .reveal-section {
    opacity: 0;
    transform: translateY(30px);
    transition: all 0.8s cubic-bezier(0.5, 0, 0, 1);
    will-change: opacity, transform;
  }
  .reveal-section.is-visible {
    opacity: 1;
    transform: translateY(0);
  }

  .chain-line {
    position: absolute;
    left: 50%;
    top: 0;
    bottom: 0;
    width: 4px;
    background: linear-gradient(to bottom, #06b6d4 50%, #e2e8f0 100%);
    transform: translateX(-50%);
    z-index: 0;
  }
`;

// --- 2. Helper Components ---

const RevealOnScroll = ({ children, delay = 0 }) => {
  const [isVisible, setIsVisible] = useState(false);
  const ref = useRef(null);

  useEffect(() => {
    const observer = new IntersectionObserver(
      ([entry]) => {
        if (entry.isIntersecting) {
          setIsVisible(true);
          observer.unobserve(entry.target);
        }
      },
      { threshold: 0.1 }
    );
    if (ref.current) observer.observe(ref.current);
    return () => { if (ref.current) observer.disconnect(); };
  }, []);

  return (
    <div ref={ref} className={`reveal-section ${isVisible ? "is-visible" : ""}`} style={{ transitionDelay: `${delay}ms` }}>
      {children}
    </div>
  );
};

const BackgroundIcon = ({ icon: Icon, className }) => (
  <div className={`absolute opacity-5 pointer-events-none select-none ${className}`} aria-hidden="true">
    <Icon className="w-full h-full" />
  </div>
);

// Helper to copy hash to clipboard
const CopyButton = ({ text }) => {
  const [copied, setCopied] = useState(false);
  const handleCopy = () => {
    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <button onClick={handleCopy} className="text-slate-400 hover:text-cyan-600 transition-colors">
      {copied ? <Check className="w-3 h-3 text-emerald-500" /> : <Copy className="w-3 h-3" />}
    </button>
  );
};

const BlockchainViewer = () => {
  const [chain, setChain] = useState([]);
  const [loading, setLoading] = useState(false);
  const [lastUpdated, setLastUpdated] = useState(null);

  const fetchChain = async () => {
    setLoading(true);
    try {
      // Connects to your Node.js Blockchain Server
      const response = await axios.get('http://localhost:3001/api/chain');
      setChain(response.data.chain || []);
      setLastUpdated(new Date());
    } catch (error) {
      console.error("Failed to fetch blockchain:", error);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchChain();
    // Optional: Auto-refresh every 30 seconds
    const interval = setInterval(fetchChain, 30000);
    return () => clearInterval(interval);
  }, []);

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-50 via-cyan-50/30 to-slate-100 font-sans pb-20">
      <style>{customStyles}</style>

      <div className="max-w-5xl mx-auto px-6 py-12">
        
        {/* ================= HEADER ================= */}
        <section className="relative flex flex-col items-center text-center mb-16">
          <BackgroundIcon icon={Database} className="w-64 h-64 -top-10 -right-10 text-cyan-500 animate-float-slow" />
          <BackgroundIcon icon={ShieldCheck} className="w-40 h-40 bottom-0 left-0 text-emerald-400 animate-float-slow" />
          
          <RevealOnScroll>
            <div className="inline-flex items-center gap-2 px-4 py-2 bg-cyan-50 text-cyan-700 rounded-full font-bold text-sm mb-6 border border-cyan-100 shadow-sm">
              <Activity className="w-4 h-4" />
              VitalChain Ledger Live
            </div>
            <h1 className="text-4xl md:text-6xl font-bold text-slate-900 mb-6 tracking-tight">
              Immutable Health Records
            </h1>
            <p className="text-xl text-slate-600 max-w-2xl mx-auto leading-relaxed mb-8">
              A transparent, cryptographically secure history of all AI diagnoses generated by the VitalCare platform.
            </p>

            {/* Stats Bar */}
            <div className="bg-white p-4 rounded-2xl shadow-lg border border-slate-100 inline-flex items-center gap-8">
              <div className="text-left">
                <p className="text-xs font-bold text-slate-400 uppercase">Total Blocks</p>
                <p className="text-2xl font-bold text-slate-900">{chain.length}</p>
              </div>
              <div className="w-px h-10 bg-slate-200"></div>
              <div className="text-left">
                <p className="text-xs font-bold text-slate-400 uppercase">Network Status</p>
                <div className="flex items-center gap-2">
                  <div className="w-2 h-2 rounded-full bg-emerald-500 animate-pulse"></div>
                  <p className="text-sm font-bold text-emerald-600">Secure</p>
                </div>
              </div>
              <div className="w-px h-10 bg-slate-200"></div>
              <button 
                onClick={fetchChain}
                className="flex items-center gap-2 px-4 py-2 bg-slate-100 hover:bg-cyan-50 text-slate-600 hover:text-cyan-700 rounded-xl transition-all font-bold text-sm"
              >
                <RefreshCw className={`w-4 h-4 ${loading ? 'animate-spin' : ''}`} />
                Refresh
              </button>
            </div>
            {lastUpdated && (
              <p className="text-xs text-slate-400 mt-4">
                Last synced: {lastUpdated.toLocaleTimeString()}
              </p>
            )}
          </RevealOnScroll>
        </section>

        {/* ================= THE CHAIN ================= */}
        <div className="relative">
          {/* Central Connecting Line (Only visible on larger screens) */}
          <div className="hidden md:block chain-line"></div>

          <div className="space-y-12 relative z-10">
            {chain.map((block, index) => {
              const isGenesis = index === 0;
              return (
                <RevealOnScroll key={block.hash} delay={index * 100}>
                  <div className="flex flex-col md:flex-row items-center gap-8">
                    
                    {/* Index Marker */}
                    <div className="hidden md:flex w-24 shrink-0 flex-col items-center justify-center text-right">
                      <span className="text-3xl font-bold text-slate-300">#{block.index}</span>
                    </div>

                    {/* The Block Card */}
                    <div className={`
                      w-full bg-white rounded-[2rem] border shadow-xl overflow-hidden transition-all hover:-translate-y-1 duration-300
                      ${isGenesis ? 'border-cyan-400 shadow-cyan-100 ring-4 ring-cyan-50' : 'border-slate-200 hover:shadow-2xl'}
                    `}>
                      
                      {/* Block Header */}
                      <div className={`px-6 py-4 border-b flex items-center justify-between ${isGenesis ? 'bg-cyan-50 border-cyan-100' : 'bg-slate-50 border-slate-100'}`}>
                        <div className="flex items-center gap-3">
                          <div className={`p-2 rounded-xl ${isGenesis ? 'bg-cyan-200 text-cyan-700' : 'bg-slate-200 text-slate-600'}`}>
                            <Box className="w-5 h-5" />
                          </div>
                          <div>
                            <h3 className="font-bold text-slate-900">
                              {isGenesis ? "Genesis Block" : "Medical Record"}
                            </h3>
                            <span className="text-xs font-mono text-slate-500">
                              {new Date(block.timestamp).toLocaleString()}
                            </span>
                          </div>
                        </div>
                        <div className="flex items-center gap-2 bg-white px-3 py-1 rounded-lg border border-slate-200 shadow-sm">
                          <ShieldCheck className={`w-4 h-4 ${isGenesis ? 'text-cyan-500' : 'text-emerald-500'}`} />
                          <span className="text-xs font-bold text-slate-600">Verified</span>
                        </div>
                      </div>

                      {/* Block Body */}
                      <div className="p-6 grid grid-cols-1 lg:grid-cols-2 gap-6">
                        
                        {/* Left: Cryptographic Data */}
                        <div className="space-y-4">
                          
                          {/* Previous Hash */}
                          <div className="group">
                            <div className="flex items-center gap-2 text-xs font-bold text-slate-400 uppercase mb-1">
                              <LinkIcon className="w-3 h-3" /> Previous Hash
                            </div>
                            <div className="font-mono text-[10px] md:text-xs text-slate-500 bg-slate-50 p-3 rounded-xl border border-slate-100 break-all group-hover:border-cyan-200 transition-colors flex items-start justify-between gap-2">
                              {block.previousHash}
                              <CopyButton text={block.previousHash} />
                            </div>
                          </div>

                          {/* Current Hash */}
                          <div className="group">
                            <div className="flex items-center gap-2 text-xs font-bold text-emerald-600 uppercase mb-1">
                              <Hash className="w-3 h-3" /> Block Hash
                            </div>
                            <div className="font-mono text-[10px] md:text-xs text-emerald-600 bg-emerald-50 p-3 rounded-xl border border-emerald-100 break-all group-hover:border-emerald-300 transition-colors flex items-start justify-between gap-2">
                              {block.hash}
                              <CopyButton text={block.hash} />
                            </div>
                          </div>
                        </div>

                        {/* Right: Payload Data */}
                        <div className="bg-slate-900 rounded-xl p-5 text-slate-300 relative overflow-hidden">
                          <div className="absolute top-0 right-0 p-3 opacity-10">
                            <FileJson className="w-16 h-16 text-white" />
                          </div>
                          <div className="relative z-10">
                            <p className="text-xs font-bold text-slate-500 uppercase mb-3 flex items-center gap-2">
                              <Activity className="w-3 h-3" /> Data Payload
                            </p>
                            
                            {isGenesis ? (
                              <p className="text-sm italic opacity-70">"Genesis Block - VitalCare Ledger"</p>
                            ) : (
                              <div className="space-y-2 font-mono text-xs md:text-sm">
                                <div className="flex justify-between border-b border-slate-800 pb-1">
                                  <span className="text-slate-500">Patient ID:</span>
                                  <span className="text-cyan-400">{block.data.patientId}</span>
                                </div>
                                <div className="flex justify-between border-b border-slate-800 pb-1">
                                  <span className="text-slate-500">Diagnosis:</span>
                                  <span className="text-white">{block.data.disease}</span>
                                </div>
                                <div className="flex justify-between">
                                  <span className="text-slate-500">Confidence:</span>
                                  <span className="text-emerald-400">{(block.data.confidence * 100).toFixed(1)}%</span>
                                </div>
                              </div>
                            )}
                          </div>
                        </div>

                      </div>
                    </div>
                  </div>
                  
                  {/* Connecting Arrow (Visual only) */}
                  {index < chain.length - 1 && (
                    <div className="flex justify-center py-4 md:hidden">
                      <ChevronDown className="w-6 h-6 text-cyan-300 animate-bounce" />
                    </div>
                  )}
                </RevealOnScroll>
              );
            })}
          </div>
        </div>

      </div>
    </div>
  );
};

export default BlockchainViewer;